[package]
name = "Rust_Project"
version = "0.1.0"
edition = "2021"

[dependencies]
rustyline = "12.0.0"
colored = "2.0.4"
clearscreen = "2.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
dialoguer = "0.11.0"
chrono = "0.4"
shellexpand = "3.1"
